TRAIN:
  ENABLE: True
  DATASET: CocoCaption
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  DATA_TYPE: image
  INPUT_CHANNEL_NUM: 3
SOLVER:
  BASE_LR: 0.0001
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  ARCH: vitb16
  MODEL_NAME: BasicClipImage
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: coco_caption
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: .
TASK: "itm"
RNG_SEED: 0