####################################################################################
# Main Config:
####################################################################################
mode: 'eval'


####################################################################################
# Modal Config:
####################################################################################
model_name: "blip-"

####################################################################################
# Dataset Config:
####################################################################################
dataset_name: "amazon-review-2023"
dataset_path: "./data/amazon-reviews-data-2023/data"

####################################################################################
# Hyperparameter Config:
####################################################################################
batch_size: 8
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.0001


####################################################################################
# Additional Config: (Normally you should not concern about this)
####################################################################################
# For dataset
need_preprocess: False
sample_num: 1