####################################################################################
# Modal Config:
####################################################################################
model_name: "mkgat"

####################################################################################
# Dataset Config:
####################################################################################
dataset_name: "amazon-review-2023"
dataset_path: "./data/amazon-reviews-data-2023/data"

####################################################################################
# Hyperparameter Config:
####################################################################################
batch_size: 8
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.0001
